# Copyright (C) 2020 Lienol <lawlienol@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Socat
LUCI_DEPENDS:=+socat

PKG_MAINTAINER:=SV <saint-wp@163.com>


# define Package/$(PKG_NAME)/conffiles
# /etc/config/socat
# endef

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature