#!/bin/sh /etc/rc.common

START=98

run_service() {

  tempfile="/usr/syncdb/tempfile"
  cronfile="/usr/syncdb/cronfile"
  keyword="syncdb"
  rm -rf $cronfile
  rm -rf $tempfile
  `crontab -l > $tempfile`
  while read -r line
  do
    if [[ "$line" == "*$keyword*" ]]
    then
      pass
    else
      `echo "$line" >> $cronfile`
    fi
  done < $tempfile


}


start() {
  run_service
  echo "* * */1 * * python /usr/syncdb/syndDB.py" >> $cronfile
  crontab -r
  crontab /usr/ddns/cronfile
}

stop() {
  run_service
  crontab -r
  crontab /usr/ddns/cronfile
}

restart() {
	start
}
