#!/bin/sh /etc/rc.common
# Copyright (C) 2020 Lienol <lawlienol@gmail.com>

START=98

CONFIG=aliddns
CONFIG_PATH=/var/etc/$CONFIG


run_service() {
#	config_get enable $1 enable
#	[ "$enable" = "" ] && return 0
	config_get AccessKeyId $1 AccessKeyId
	[ "AccessKeyId" = "" ] && return 0
	config_get AccessKeySecret $1 AccessKeySecret
	[ "AccessKeySecret" = "" ] && return 0
	config_get Subdomain $1 Subdomain
	config_get Domain $1 Domain
	config_get Iptype $1 Iptype
	config_get TTL $1 TTL
	config_get DnsServer $1 DnsServer

	echo "*/5 * * * * /bin/bash /usr/ddns/ddns.sh $AccessKeyId $AccessKeySecret $Subdomain $Domain $Iptype $TTL $DnsServer" >> /usr/ddns/cronfile



}
conf_set(){
  cronfile="/usr/ddns/cronfile"
  keyword="ddns"
  rm -rf $cronfile
  `crontab -l > $cronfile`
  for line in $(cat $cronfile)
  do
      if [[ $line == *$keyword* ]]
      then
          pass
      else
          `echo $line >> $cronfile`
      fi
  done
}

start() {
#	enable=$(uci -q get $CONFIG.@global[0].enable)
#	if [ "$enable" = "0" ];then
#		stop_service
#	else
#		mkdir -p $CONFIG_PATH
#		rm -f /var/etc/$CONFIG.port
#		config_load $CONFIG
#		config_foreach run_service "config"
	conf_set
  config_load $CONFIG
  config_foreach run_service "alikey"
  crontab -r
  crontab /usr/ddns/cronfile
#	fi
}

stop() {
  conf_set
  crontab -r
  crontab /usr/ddns/cronfile
}

restart() {
	start
}
