#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.socatui
	set firewall.socatui=include
	set firewall.socatui.type=script
	set firewall.socatui.path=/var/etc/socatui.include
	set firewall.socatui.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@socatui[-1]
	add ucitrack socatui
	set ucitrack.@socatui[-1].init=SocatUI
	commit ucitrack
EOF

chmod +x /etc/init.d/socatui
rm -rf /tmp/luci-*cache
exit 0
