#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.socat
	set firewall.socat=include
	set firewall.socat.type=script
	set firewall.socat.path=/var/etc/socat.include
	set firewall.socat.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@socat[-1]
	add ucitrack socat
	set ucitrack.@socat[-1].init=SocatUI
	commit ucitrack
EOF

chmod +x /etc/init.d/SocatUI
rm -rf /tmp/luci-*cache
exit 0
