#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=all SV-wrt need software
LUCI_DEPENDS:=+luci-app-wol +luci-app-socat +luci-app-cpu +luci-app-aliddns +luci +nginx-all-module
PKG_NAME:=luci-app-all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
